export const saveNavItem = async () => { };
export const updateNavItem = async () => { };
export const deleteNavItem = async () => { };
export const saveNews = async () => { };
export const updateNews = async () => { };
export const deleteNews = async () => { };
export const saveDocument = async () => { };
export const updateDocument = async () => { };
export const deleteDocument = async () => { };
export const savePage = async () => ({ Id: 1, Modified: new Date().toISOString() });
export const updatePage = async () => { };
export const deletePage = async () => { };
export const saveContainer = async () => ({ Id: 1 });
export const updateContainer = async () => { };
export const deleteContainer = async () => { };
export const getPages = async () => [];
export const getContainersByPageId = async () => [];
export const getNavigation = async () => [];
export const getNews = async () => [];
export const getDocuments = async () => [];
export const getImages = async () => [];
export const getGlobalSettings = async () => ({});
